apiVersion: v1
kind: Service
metadata:
  name: lab-numbers-web
spec:
  selector:
    app: lab-numbers-web
  ports:
    - port: 8088
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: numbers-api
spec:
  ports:
    - port: 80
  selector:
    app: lab-numbers-api
    version: v1
  type: ClusterIP
