apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  labels:
    kiamol: ch07-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      initContainers:
        - name: init-config
          image: kiamol/ch03-sleep
          command: ['sh', '-c', "echo '#!/bin/sh\ndotnet Pi.Web.dll -m web' > /init/startup.sh && chmod +x /init/startup.sh"]
          volumeMounts:
            - name: config-dir
              mountPath: "/init"
      containers:
        - name: web
          image: kiamol/ch05-pi
          command: ["/init/startup.sh"]
          volumeMounts:
            - name: config-dir
              mountPath: "/init"
          ports:
            - containerPort: 80
              name: http
        - name: server
          image: kiamol/ch03-sleep
          command: ['sh', '-c', 'while true; do echo -e "HTTP/1.1 200 OK\nContent-Type: text/plain\nContent-Length: 9\n\n$(1234567)" | nc -l -p 8080; done']
          ports:
            - containerPort: 8080
              name: health
      volumes:
        - name: config-dir
          emptyDir: {}
